CREATE DATABASE Convert_ERD;
USE Convert_ERD;

CREATE TABLE PHIEUXUAT(
    SoPX INT PRIMARY KEY,
    NgayXuat DATETIME 
);

CREATE TABLE PHIEUNHAP(
    SoPN INT PRIMARY KEY,
    NgayNhap DATETIME
);

CREATE TABLE VATTU(
    MaVTU VARCHAR(20) PRIMARY KEY,
    TenVTU VARCHAR(50) NOT NULL
);

CREATE TABLE NHACC(
    MaNCC VARCHAR(20) PRIMARY KEY,
    TenNCC VARCHAR(30) NOT NULL,
    DiaChi VARCHAR(50),
    SDT VARCHAR(10) 
);

CREATE TABLE DONDH(
    SoDH INT PRIMARY KEY,
    NgayDH DATETIME,
    MaNCC VARCHAR(20),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);


CREATE TABLE CHITIET_PHIEUXUAT(
    SoPX INT,
    MaVTU VARCHAR(20),
    DonGiaSX DECIMAL(10,2),
    SoLuongXuat INT,
    PRIMARY KEY(SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CHITIET_PHIEUNHAP(
    SoPN INT,
    MaVTU VARCHAR(20),
    DGNhap DECIMAL(10,2),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CHITIET_DONDH(
    SoDH INT,
    MaVTU VARCHAR(20),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
